name: Build tzdata
on: push

jobs:
  build-job:
    name: build source code
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build.outputs.version }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: build
        run: |
          python3 version.py
          echo $(cat /tmp/version)
          echo "::set-output name=version::$(echo $(cat /tmp/version))"
        shell: bash


      - name: upload
#        if: ${{ steps.build.outputs.version }}
        uses: actions/upload-artifact@master
        with:
          name: ${{steps.build.outputs.version}}_zoneinfo.zip
          path: ${{github.workspace}}/${{steps.build.outputs.version}}_zoneinfo.zip

#      - name: release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.TOKEN }}
#          file: ${{github.workspace}}/${{env.VERSION}}_zoneinfo.zip
#          asset_name: ${{env.VERSION}}_zoneinfo.zip
#          tag: ${{env.VERSION}}
#          overwrite: true
#          body: "release ${{env.VERSION}}"