name: Build tzdata
on: push

jobs:
  build-job:
    name: build source code
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: build
        run: |
          /usr/bin/bash build.sh
