name: generate tzdb
#on:
#  schedule:
#    - cron: '*/30 12 * * *'
on: push

jobs:
  build-job:
    name: build source code
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - id: build
        name: build code
        run: |
          python3 scripts/version.py
          VERSION="$(cat /tmp/version)"
          echo "::set-output name=version::$VERSION"
          echo "version: ${{ steps.build.outputs.version }}"
        shell: bash

      - name: upload tzdb
        if: ${{ steps.build.outputs.version }}
        uses: actions/upload-artifact@master
        with:
          name: ${{steps.build.outputs.version}}_zoneinfo.zip
          path: ${{github.workspace}}/${{steps.build.outputs.version}}_zoneinfo.zip

      - name: release version
        if: ${{ steps.build.outputs.version }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: ${{github.workspace}}/${{steps.build.outputs.version}}_zoneinfo.zip
          asset_name: ${{steps.build.outputs.version}}_zoneinfo.zip
          tag: ${{steps.build.outputs.version}}
          overwrite: true
          body: "release tzdb ${{steps.build.outputs.version}}"